name: Hello world workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: write
jobs:
  hello:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo "Hello world"
        shell: bash
  goodbey:
    runs-on:  ubuntu-latest
    steps:
      - name: goodbye world
        run: echo "Goodbye world"
        shell: bash
  test:
    name: 'Run node js'
    working-directory: test_cicd
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: 'Checkout repository'

    - name: 'Install Dependencies'
      run: npm install

    - name: 'Run nodejs'
      run: node index.js
      
